### ISSUE TITLE
Zend View behaviour in a Swoole http server

### ISSUE THREAD

**Issue by jgalvezsoax** [zendframework/zend-expressive-swoole#34]
Hello,

I wrote this question some days ago in StackOverflow but still, I haven't got an answer. I hope you could help us.

We are facing a strange behaviour with a Zend Expressive application using Zend View and running in a swoole http server. This behaviour is related with the Singleton pattern.

We have configured Zend Expressive to run in a swoole http server - https://docs.zendframework.com/zend-expressive-swoole/ - and all APIs programmed work without problems (swoole is a rocket!)

But we have tried to go to the next step and we have tried to execute a web interface through the swoole http server. 

There, it's where we found the strange behaviour. To simplify my question (we use a lot of view helpers), our web interfaces work with Zend View and use the headTitle helper. When you load the web interface the first time everything is working well but when you reload the page you can see that the meta title is duplicated.

Our handler is next

    public function handle(ServerRequestInterface $request) : ResponseInterface
    {
        $data = [
            "rand" => rand(1000, 9999),
            "time" => date("Y-m-d H:i:s")
        ];
        return new HtmlResponse($this->template->render('app::my-view', $data));
    }

Our view is next

    <?php $this->headTitle('My Page'); ?>
    <b>Rand</b>: <?php echo $rand; ?><br>
    <b>Time</b>: <?php echo $time; ?><br>
    <hr>

Searching in Google we found in https://framework.zend.com/blog/2018-03-21-expressive-swoole.html that Zend's team had faced a similar problem:

> With an async server, however, the same instance will be used on each
> and every request. Generally, manipulations of PSR-7 message instances
> will create new instances, as the interfaces they implement are
> specified as immutable. Unfortunately, due to technical limitations of
> the PHP language, we were unable to make the body of response messages
> immutable. This means that if one process writes to that body, then a
> subsequent process — or even those executing in parallel! — will
> receive the same changes. This can lead to, in the best case scenario,
> duplicated content, and, in the worst, provide incorrect content or
> perform information leaking!

And they had solved that

> To combat these situations, we modified the
> Psr\Http\Message\ResponseInterface service we register with the
> dependency injection container: it now returns not an instance of the
> interface, but a factory capable of producing an instance

But inspecting the Zend Framework classes we saw that we had another problem because the solution was implemented in the code and all requests made to apis were correct 

in zend-expressive-swoole/src/ConfigProvider.php you can see

    ServerRequestInterface::class         => ServerRequestSwooleFactory::class,

Then we change our point of view and inspect the zend view helpers and we found that the view helper HeadTitle extends from a Container\AbstractStandalone

    file: zend-view/src/Helper/HeadTitle
    class HeadTitle extends Placeholder\Container\AbstractStandalone

Looking in this AbstractStandalone we discovered that in the constructor method a container is loaded through a singleton

    file: zend-view/src/Helper/Placeholder\Container\AbstractStandalone
    public function getContainer()
    {
        if (! $this->container instanceof AbstractContainer) {
            $this->container = new $this->containerClass();
        }
        return $this->container;
    }

Here is the problem. With the Zend Expressive Swoole module, every request and every response are independent but the same Singleton container is used again and again.

Have you faced this problem? How did you solve this?

**Comment by samuelnogueira** [comment]
We faced similar problem, but we don't have a nice solution for them, especially if we consider parallel requests handling by the same swoole worker.
Nonetheless, what we're doing as a workaround, is forcing those view containers to be recreated on each request in a middleware:
```php
    /**
     * {@inheritdoc}
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $layout  = clone $this->layout;
        $this->phpRenderer->viewModel()->setRoot($layout);
        $this->phpRenderer->headTitle()->deleteContainer();
        $this->phpRenderer->headMeta()->deleteContainer();
        $this->phpRenderer->seo()->reset();
    }
```

**Comment by huangzhhui** [comment]
@samuelnogueira This solution could works in Process mode, but not works in Coroutine mode, we could use `\Swoole\Coroutine::getuid()` method to get an unique coroutine id to locate the container, but this way have to modify zend-view.

**Comment by jgalvezsoax** [comment]
@samuelnogueira It works for our testing platform. Thanks for your help.

@huangzhhui since my question is answered I think it's better to close this issue but the comment you did it's very interesting... Thanks again

**Comment by weierophinney** [comment]
Honestly, this is one of the problem areas we have identified. A similar one is exposed by the `TemplateRendererInterface` of zend-expressive-template, as it allows you to inject new "default" parameters into a template renderer instance; this can cause state issues similar to what you describe above.

The solution? We don't have one yet. There are a few approaches you can consider, though.

- Be picky about the template engine you use, and pick those that tend to operate in a stateless fashion. [PlatesPHP](https://platesphp.com) has proven to be good in that regard, and will be mostly familiar to zend-view users.
- Do not use `addDefaultParam()` in `TemplateRendererInterface` other than in factories and delegators. Within middleware, pass pipeline-specific values via server attributes, and in your handlers, merge those with any variables you intend to pass to the renderer.
- Worst-case scenario, instead of injecting the template engine directly in your handlers, inject a _factory_ that can produce it. This will allow you to have an instance per-request, which will solve concurrency issues entirely.

**Comment by weierophinney** [comment]
@huangzhhui It's not an issue with _this_ package, it's an issue with each of:

- zendframework/zend-expressive-zendviewrenderer
- zendframework/zend-expressive-template

The problem is that zend-view _retains state_. In normal PHP execution, this is not a problem, as everything is discarded at the end of the request. With Swoole, however, we end up re-using the instances for each request, and state accumulates in the various helpers.

Additionally, we have documented using the `addDefaultParam()` method from zend-expressive-template _within middleware_ to add things like pipeline-specific template variables. This is not a good practice when using Swoole, as doing so changes the state of the _renderer_, which is a shared service. As such, we need to document that users should instead push these into a server attribute, and then fetch that server attribute and merge the result into the variables they pass to the renderer.

In each case, though, the problem is not _this package_, but how other packages act when run under Swoole.

**Comment by huangzhhui** [comment]
@weierophinney 
In the others frameworks or applications based on Swoole, to use Singleton mode, will never to modify the properties value in the singleton instance, the singleton instance should be immutable, it is first principle, and the application will provide a `RequestContext` to handle the variables that persisted in a single request, it is actually a Container to save any variables, but will locate the specified container for every request,  according to a Request ID, it is `\Swoole\Coroutine::getuid()` when the server running in coroutine mode, and `RequestContext` will destroy the context in the end of request.
Reference for you.

**Comment by weierophinney** [comment]
@huangzhhui Could you point me to some examples, please? If we can solve it at the server level without needing to change existing application code, that would be the best possible solution.

**Comment by azjezz** [comment]
@weierophinney i suggest that expressive have a `ResetInterface` with one method `reset` to reset all objects to their initial status after the request have been handled, symfony already did this ( https://github.com/symfony/symfony/blob/master/src/Symfony/Contracts/Service/ResetInterface.php), all expressive components (e.g: zend-expressive-view) should implement this interface and the runner can reset all implementations of the ResetInterface in the end of the request.

another solution would be event dispatching, where we can set events before and after the request have been handled.

**Comment by huangzhhui** [comment]
@weierophinney @azjezz 
No, to solve this problem, we have to change the library code.
When the server running in Process mode, https://github.com/zendframework/zend-expressive-swoole/issues/34#issuecomment-424700305 is a common solution.
But when the server running in Coroutine mode, we have to use a Coroutine ID to identify the different request, no matter what reset the objects to the initial status after or before the request, because the worker will handle the requests in the same time.

**Comment by samuelnogueira** [comment]
@azjezz if using zend-servicemanager, this "reset" behavior is already available by declaring services as non-shared: https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/#shared
As @huangzhhui has pointed out, this still doesn't solve any issues regarding instances being shared among requests if using Swoole in Coroutine mode (or any single process parallel execution mode in any http server for that matter).

**Comment by weierophinney** [comment]
@samuelnogueira Declaring services as non-shared defeats the purpose of having a DI container in most cases, as the idea is that you have the _same instances_ passed as dependencies generally. This saves on memory, and, in cases such as zend-db and zend-cache, ensures you only have one connection to a service open at any given time. I definitely do **not** recommend that approach.

**Comment by weierophinney** [comment]
@huangzhhui Thanks for the example! I need to figure out how this would interact with the DI container (as services are pulled from there); however, it gives me a starting place.
