### ISSUE TITLE
The command "start" does not exist.

### ISSUE THREAD

**Issue by guilherme90** [zendframework/zend-expressive-swoole#65]
I can not run the swoole. He says that the command "start" does not exist.

### Code to reproduce the issue
```sh
$ ./vendor/bin/zend-expressive-swoole start
```

### Expected results
start the server with swoole. I am using Cwgyn 64bit.

### Actual results
Return a error 

> The command "start" does not exist.

**Comment by guilherme90** [comment]
![Capture](https://user-images.githubusercontent.com/2879939/54548576-fbc5cb80-4986-11e9-814e-df724bc1e956.PNG)

**Comment by weierophinney** [comment]
What version have you installed? Can you copy and paste the result of `composer show`, please?

**Comment by guilherme90** [comment]
Sure!

Expressive installed: 3.2.1
More details: https://gist.github.com/guilherme90/27c7e45cd50936bbbd1920042aacbb0b

**Comment by weierophinney** [comment]
This looks like it may be a problem with Cygwin and/or your shell. Can you look at the following link and see if it helps you resolve the issue:

- https://stackoverflow.com/questions/20307618/symfony2-cygwin-cli-php-commands-error

**Comment by guilherme90** [comment]
Well, I'm trying and unsuccessful. But it's just the one I'm having trouble with. If I execute commands like: `composer expressive module:create ...`, it works normally.

**Comment by weierophinney** [comment]
So far, I am unable to reproduce it; I have a bare Expressive skeleton in which I've installed zend-expressive-swoole 2.4.0, and the `start` command works as expected. The only part that differs that I can tell is the operating sytem; I'm on Ubuntu Linux. That said, the OS should only be an issue for certain PHP extensions.

The other possibility: are you running the command from within your project root directory? If not, that would be a problem; otherwise, it _should_ work.

**Comment by guilherme90** [comment]
I agree, I'm thinking it's a problem with my OS. I'm using Windows 10. And yes, I'm running at the root of the project.

Can you do some testing, virtualizing Win10, installing Cygwin? 
Thanks.

**Comment by weierophinney** [comment]
> Can you do some testing, virtualizing Win10, installing Cygwin?

Honestly, no. Doing so requires a ton of time: download time; initial virtual image initialization; building and installing cygwin once I have a running vm; finding and installing an appropriate PHP package from cygwin; hunting down all dependencies needed to build the Swoole extension once I have; building the swoole extension; and that's all before I can even create a project to test against. This would likely be a 4-8 hour project, to solve an issue for a non-production system. I simply cannot justify it, unfortunately.

You have two other options:

- Use the Windows Subsystem for Linux (WSL); versions from last fall at least [worked with the Ubuntu 18.04 version used by WSL](http://www.codeblogbt.com/archives/152301), though it's possible recent versions do not.
- Use virtualbox or vmware to run a linux VM, and use the PHP in the VM. One good option is Laravel Homestead (we've even [documented running Expressive on it](https://framework.zend.com/blog/2018-05-16-homestead.html)).

Otherwise, see if you can find somebody else running Cygwin within the Slack, and see if they can help you debug.

**Comment by guilherme90** [comment]
Right!

So, you can close this issue. Thanks.
