### ISSUE TITLE
Psr3AccessLogDecorator does not replace placeholders

### ISSUE THREAD

**Issue by grizzm0** [zendframework/zend-expressive-swoole#68]
The Psr3AccessLogDecorator does not replace placeholders in Psr3AccessLogDecorator::log().

https://github.com/zendframework/zend-expressive-swoole/blob/69c36f044aa22cf0b202eedeb3fc8f31cfb6f023/src/Log/Psr3AccessLogDecorator.php#L134-L137

https://github.com/zendframework/zend-expressive-swoole/blob/69c36f044aa22cf0b202eedeb3fc8f31cfb6f023/src/Log/StdoutLogger.php#L98-L105

**Comment by grizzm0** [comment]
Should we just copy/paste the code or move it to a re-useable method or abstract class?

**Comment by weierophinney** [comment]
The way PSR-3 is worded is that values provided in `$context` MAY be used to replace any corresponding placeholders in the message (see [section 1.2 of the PSR-3 spec](https://www.php-fig.org/psr/psr-3/#12-message)). The `StdoutLogger` we supply does this, because it's useful, but implementations do not NEED to.

If you use Monolog, for instance, you have to add its `PsrLogMessageProcessor` to the instance for it to do any replacements. Others, such as [apix/log](https://github.com/apix/log) do it out of the box.

As such, if and how placeholders are replaced is up to the PSR-3 logging implementation you choose. If the instance you are using does not support them, decorate your logger's `log()` method to do so.
